version: '3.9'
services:
  app1:
    build: ./web-app-1/.
    image: ishwarik7/web-app-1
    container_name: web_app_1
    ports:
      - "8080:3000"
    volumes:
      - ./src:/web-app-1
    healthcheck:
      test: curl --fail http://localhost:3000 || exit 1
      interval: 30s
      timeout: 3s
      retries: 5
      start_period: 10s
    networks:
      my-network:
        aliases:
          - webapp1
  app2:
    build: ./web_app_2/.
    image: ishwarik7/web-app-2
    container_name: web_app_2
    expose:
      - "3001"
    volumes:
      - ./src:/web-app-2
    healthcheck:
      test: curl --fail http://localhost:3001 || exit 1
      interval: 30s
      timeout: 3s
      retries: 5
      start_period: 10s
    networks:
      my-network:
        aliases:
          - webapp2
networks:
  my-network:
    driver: bridge